# -*- coding: utf-8 -*-
"""Copy of CIS412 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLld7KBPV05Lrlu0xisez3rExnNfp6lG
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/superstore_data.csv")

df.head()
df.shape
df.info()
df.describe()

df.head()

df.isnull().sum()

#Handle Null Values
df['Income'] = df['Income'].fillna(df['Income'].median())

#Convert to age
import datetime

current_year = datetime.datetime.now().year
df['Age'] = current_year - df['Year_Birth']

df = df.drop('Year_Birth', axis=1)

#Remove unrealistic ages
df = df[(df['Age'] > 18) & (df['Age'] < 90)]

#Converting dt customer to tenure
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])

df['Customer_Tenure'] = (pd.Timestamp.now() - df['Dt_Customer']).dt.days

df = df.drop('Dt_Customer', axis=1)

#Create total spending
spending_cols = [
    'MntWines','MntFruits','MntMeatProducts',
    'MntFishProducts','MntSweetProducts','MntGoldProds'
]

df['Total_Spending'] = df[spending_cols].sum(axis=1)

# Create total purchases
df['Total_Purchases'] = (
    df['NumWebPurchases'] +
    df['NumCatalogPurchases'] +
    df['NumStorePurchases']
)

df = df.drop('Id', axis=1)

# Dummy Encoding
df = pd.get_dummies(df, columns=['Education', 'Marital_Status'], drop_first=True)

#Checking target
df['Response'].value_counts()

import matplotlib.pyplot as plt

counts = df['Response'].value_counts().sort_index()

plt.figure(figsize=(6,4))
counts.plot(kind='bar')
plt.title('Class Imbalance in Response')
plt.xlabel('Response Class')
plt.ylabel('Number of Customers')
plt.xticks([0, 1], ['0 = No', '1 = Yes'], rotation=0)
plt.show()

# Train.Test split
from sklearn.model_selection import train_test_split

X = df.drop('Response', axis=1)
y = df['Response']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

importance_gb = pd.Series(gb.feature_importances_, index=X.columns)
importance_gb.sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

importance_gb.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Customer Response")
plt.gca().invert_yaxis()
plt.show()

import joblib
from sklearn.ensemble import GradientBoostingClassifier

# Re-initialize and train the Gradient Boosting model for saving
# This ensures 'gb' is always defined when this cell is run independently
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

# Save the Gradient Boosting model
joblib.dump(gb, 'gradient_boosting_model.joblib')

# Also save the column names (features) to ensure consistency when deploying
joblib.dump(X.columns, 'model_features.joblib')

print("Gradient Boosting model and feature names saved as 'gradient_boosting_model.joblib' and 'model_features.joblib'")

"""Now that the model is saved, you need to create a Streamlit application. This involves a separate Python file (e.g., `app.py`) where you'll load the model, define the user interface for input, and display predictions. Below is the content for your `app.py` file. You can copy this code and save it as `app.py` in your local environment. Make sure to have `streamlit` and `scikit-learn` installed (`pip install streamlit scikit-learn`)."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load the trained model and features
# model = joblib.load('gradient_boosting_model.joblib')
# model_features = joblib.load('model_features.joblib')
# 
# st.title('Customer Response Prediction App')
# st.write('Enter customer details to predict their response to a campaign.')
# 
# # Create input widgets for each feature
# # You will need to carefully consider the range and type of each input
# # For simplicity, let's create numerical inputs for now.
# # In a real app, you'd want to handle categorical features with select boxes/radio buttons
# # and ensure data types match your training data.
# 
# st.header('Customer Information')
# 
# income = st.number_input('Income', min_value=0.0, value=50000.0, step=100.0)
# kidhome = st.slider('Number of Kids at Home', 0, 2, 0)
# teenhome = st.slider('Number of Teens at Home', 0, 2, 0)
# recency = st.number_input('Days since last purchase (Recency)', min_value=0, max_value=99, value=50)
# mnt_wines = st.number_input('Amount spent on Wines', min_value=0, value=100)
# mnt_fruits = st.number_input('Amount spent on Fruits', min_value=0, value=10)
# mnt_meat_products = st.number_input('Amount spent on Meat Products', min_value=0, value=50)
# mnt_fish_products = st.number_input('Amount spent on Fish Products', min_value=0, value=10)
# mnt_sweet_products = st.number_input('Amount spent on Sweet Products', min_value=0, value=10)
# mnt_gold_prods = st.number_input('Amount spent on Gold Products', min_value=0, value=20)
# num_deals_purchases = st.number_input('Number of purchases with a deal', min_value=0, value=2)
# num_web_purchases = st.number_input('Number of web purchases', min_value=0, value=3)
# num_catalog_purchases = st.number_input('Number of catalog purchases', min_value=0, value=1)
# num_store_purchases = st.number_input('Number of store purchases', min_value=0, value=4)
# num_web_visits_month = st.number_input('Number of web visits per month', min_value=0, value=5)
# complain = st.selectbox('Has the customer complained?', [0, 1], index=0)
# age = st.number_input('Age', min_value=18, max_value=90, value=40)
# customer_tenure = st.number_input('Customer Tenure (days)', min_value=0, value=1000)
# total_spending = mnt_wines + mnt_fruits + mnt_meat_products + mnt_fish_products + mnt_sweet_products + mnt_gold_prods
# total_purchases = num_web_purchases + num_catalog_purchases + num_store_purchases
# 
# # Education and Marital Status (example for handling dummy variables)
# st.header('Demographics')
# education = st.selectbox('Education', ['Graduation', 'PhD', 'Master', '2n Cycle', 'Basic'])
# marital_status = st.selectbox('Marital Status', ['Married', 'Together', 'Single', 'Divorced', 'Widow', 'Alone', 'YOLO', 'Absurd'])
# 
# # Prepare input data for prediction
# input_data = pd.DataFrame(columns=model_features)
# 
# # Initialize with zeros for all dummy variables
# for col in model_features:
#     input_data.loc[0, col] = 0
# 
# input_data.loc[0, 'Income'] = income
# input_data.loc[0, 'Kidhome'] = kidhome
# input_data.loc[0, 'Teenhome'] = teenhome
# input_data.loc[0, 'Recency'] = recency
# input_data.loc[0, 'MntWines'] = mnt_wines
# input_data.loc[0, 'MntFruits'] = mnt_fruits
# input_data.loc[0, 'MntMeatProducts'] = mnt_meat_products
# input_data.loc[0, 'MntFishProducts'] = mnt_fish_products
# input_data.loc[0, 'MntSweetProducts'] = mnt_sweet_products
# input_data.loc[0, 'MntGoldProds'] = mnt_gold_prods
# input_data.loc[0, 'NumDealsPurchases'] = num_deals_purchases
# input_data.loc[0, 'NumWebPurchases'] = num_web_purchases
# input_data.loc[0, 'NumCatalogPurchases'] = num_catalog_purchases
# input_data.loc[0, 'NumStorePurchases'] = num_store_purchases
# input_data.loc[0, 'NumWebVisitsMonth'] = num_web_visits_month
# input_data.loc[0, 'Complain'] = complain
# input_data.loc[0, 'Age'] = age
# input_data.loc[0, 'Customer_Tenure'] = customer_tenure
# input_data.loc[0, 'Total_Spending'] = total_spending
# input_data.loc[0, 'Total_Purchases'] = total_purchases
# 
# # Set dummy variables based on selection
# if education != 'Graduation': # Graduation is the dropped first column
#     edu_col = f'Education_{education}'
#     if edu_col in input_data.columns:
#         input_data.loc[0, edu_col] = 1
# 
# if marital_status != 'Alone': # Assuming 'Alone' or similar was dropped, adjust if different
#     marital_col = f'Marital_Status_{marital_status}'
#     if marital_col in input_data.columns:
#         input_data.loc[0, marital_col] = 1
# 
# # Ensure all columns are in the correct order and type
# input_data = input_data[model_features].astype(float)
# 
# # Make prediction
# if st.button('Predict Response'):
#     prediction_proba = model.predict_proba(input_data)[:, 1][0] # Probability of class 1
#     prediction = model.predict(input_data)[0]
# 
#     st.subheader('Prediction Results')
#     if prediction == 1:
#         st.success(f'Customer is likely to respond! (Probability: {prediction_proba:.2f})')
#     else:
#         st.info(f'Customer is unlikely to respond. (Probability: {prediction_proba:.2f})')
# 
#     st.write('---')
#     st.write('### Feature Importances (Top 10)')
#     # This part requires having feature importances available,
#     # which we can get from the trained model if it supports it (like GradientBoostingClassifier)
#     if hasattr(model, 'feature_importances_'):
#         importance_df = pd.DataFrame({
#             'Feature': model_features,
#             'Importance': model.feature_importances_
#         }).sort_values(by='Importance', ascending=False).head(10)
#         st.bar_chart(importance_df.set_index('Feature'))
#

# =============================================================================
# SECTION 6 — DEPLOYMENT
# =============================================================================
#
# OVERVIEW
# --------
# Our Gradient Boosting Classifier is deployed as an interactive Streamlit
# web application. The app allows marketing teams to:
#   1. Upload new customer CSV data and automatically retrain the model.
#   2. View model performance metrics (Accuracy, Precision, Recall, F1).
#   3. Explore the Top 10 features that drive campaign response.
#   4. Enter individual customer attributes and receive a live prediction
#      with a confidence probability.
#
# DEPLOYMENT ARCHITECTURE
# -----------------------
#   Phase 1 — Data & Training
#     • User uploads superstore_data.csv via the Streamlit sidebar.
#     • The full preprocessing pipeline runs automatically (null handling,
#       age conversion, tenure calculation, feature engineering, encoding).
#     • The Gradient Boosting model is trained in-session and cached to
#       avoid unnecessary re-training on reruns.
#
#   Phase 2 — Prediction Interface
#     • Marketing analysts enter customer attributes (income, age, recency,
#       spending, household size, etc.) via sliders and input fields.
#     • The model returns: predicted class (0 or 1) + probability score.
#     • A clear visual decision card is shown alongside an actionable
#       recommendation for the marketing team.
#
#   Phase 3 — Monitoring & Maintenance
#     • After each campaign, actual outcomes are compared to predictions
#       to compute real-world F1-score.
#     • Model is retrained quarterly as new transaction data accumulates.
#     • Model versions are tracked (e.g., MLflow or DVC) to allow rollback
#       if a new version underperforms.
#
# HOW TO RUN LOCALLY
# ------------------
#   pip install streamlit scikit-learn pandas matplotlib
#   streamlit run streamlit_app.py
#
# =============================================================================


# =============================================================================
# ETHICAL CONSIDERATIONS
# =============================================================================
#
# 1. FAIRNESS & BIAS
#    The model learns from historical marketing data. If past campaigns were
#    disproportionately aimed at — or withheld from — certain groups (e.g.,
#    lower-income customers or specific marital statuses), those patterns get
#    encoded into the model. We regularly audit the feature importance chart
#    to ensure sensitive attributes like Age or Marital_Status are NOT the
#    top drivers of predictions. If they appear in the top 3, we investigate
#    and consider removing or transforming those inputs.
#
# 2. TRANSPARENCY & EXPLAINABILITY
#    Gradient Boosting is not easily human-interpretable on its own. To
#    maintain transparency:
#      • We publish the Top 10 Feature Importance chart in the app so
#        stakeholders can see what the model is relying on.
#      • Probability scores are shown alongside every prediction so analysts
#        understand how confident the model is.
#      • For high-stakes decisions, SHAP (SHapley Additive exPlanations)
#        can be added to explain individual-level predictions.
#
# 3. DATA PRIVACY (GDPR / CCPA)
#    Customer data includes income, purchase history, and household
#    demographics — all of which are personally sensitive. Mitigations:
#      • No direct PII (name, email, address) is used as a model feature.
#      • Data is processed in-session only; nothing is persisted to a server.
#      • In a production pipeline, data must be anonymized or pseudonymized
#        before ingestion into the model.
#
# 4. INFORMED CONSENT
#    Customers whose data trains the model should be notified via privacy
#    policy that their purchase behavior influences which marketing campaigns
#    they receive. This aligns with GDPR Article 22 on automated
#    decision-making affecting individuals.
#
# =============================================================================


# =============================================================================
# RISKS & MITIGATIONS
# =============================================================================
#
# RISK 1 — MODEL DRIFT
#   Description : Consumer behavior changes over time due to economic shifts,
#                 seasons, and trends. A model trained on older data may
#                 perform poorly on future campaigns.
#   Mitigation  : Schedule quarterly retraining with the latest campaign data.
#                 Monitor F1-score (class 1) monthly against real outcomes.
#                 Set an alert if F1 drops below 0.55 to trigger early retraining.
#
# RISK 2 — CLASS IMBALANCE
#   Description : Only ~15% of customers respond (class 1). A naive model can
#                 reach ~85% accuracy by always predicting "No," which is
#                 useless for identifying actual responders.
#   Mitigation  : We use stratify=y in train_test_split to preserve class ratios.
#                 We report Recall and F1 for class 1, not just overall accuracy.
#                 Additional options: SMOTE oversampling or class_weight tuning.
#
# RISK 3 — OVERRELIANCE ON MODEL OUTPUT
#   Description : Marketing teams may treat predictions as absolute, removing
#                 human judgment and potentially alienating customers.
#   Mitigation  : Frame the tool as a prioritization aid, not a final decision.
#                 Show confidence scores prominently so analysts can apply
#                 discretion on borderline cases (e.g., 51% confidence).
#                 Require human sign-off before excluding any customer segment.
#
# RISK 4 — DATA LEAKAGE
#   Description : Features like Total_Spending could include post-campaign
#                 transactions if the dataset is not filtered correctly,
#                 causing inflated and misleading performance metrics.
#   Mitigation  : Enforce a strict temporal cutoff — only include customer
#                 data recorded before the campaign launch date. Validate
#                 the Dt_Customer date range before every training run.
#
# RISK 5 — FEEDBACK LOOP
#   Description : If the model always targets the same segments, those are
#                 the only groups measured for response — creating a blind
#                 spot for untested customer groups.
#   Mitigation  : Randomly include a small holdout group (~5%) in each
#                 campaign regardless of model prediction, to continuously
#                 collect unbiased ground-truth data from the full population.
#
# =============================================================================


# --- Save the trained model for production use ---

import joblib
import json

# Save Gradient Boosting model to disk
joblib.dump(gb, 'campaign_response_model.pkl')
print("✅ Model saved as 'campaign_response_model.pkl'")

# Save feature column order to ensure consistent input format at prediction time
with open('feature_columns.json', 'w') as f:
    json.dump(X.columns.tolist(), f)
print("✅ Feature columns saved as 'feature_columns.json'")

# To load and use the model later:
#   gb_loaded = joblib.load('campaign_response_model.pkl')
#   y_pred = gb_loaded.predict(X_new)