# -*- coding: utf-8 -*-
"""Copy of Untitled7.ipynb — WITH DEPLOYMENT SECTION

Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1bstS7nrJAAA3A2kncJII2mfNAncnNlYW
"""

import pandas as pd
df = pd.read_csv("/content/superstore_data.csv")

df.head()
df.shape
df.info()
df.describe()

df.head()

df.isnull().sum()

#Handle Null Values
df['Income'] = df['Income'].fillna(df['Income'].median())

#Convert to age
import datetime

current_year = datetime.datetime.now().year
df['Age'] = current_year - df['Year_Birth']

df = df.drop('Year_Birth', axis=1)

#Remove unrealistic ages
df = df[(df['Age'] > 18) & (df['Age'] < 90)]

#Converting dt customer to tenure
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])

df['Customer_Tenure'] = (pd.Timestamp.now() - df['Dt_Customer']).dt.days

df = df.drop('Dt_Customer', axis=1)

#Create total spending
spending_cols = [
    'MntWines','MntFruits','MntMeatProducts',
    'MntFishProducts','MntSweetProducts','MntGoldProds'
]

df['Total_Spending'] = df[spending_cols].sum(axis=1)

# Create total purchases
df['Total_Purchases'] = (
    df['NumWebPurchases'] +
    df['NumCatalogPurchases'] +
    df['NumStorePurchases']
)

df = df.drop('Id', axis=1)

# Dummy Encoding
df = pd.get_dummies(df, columns=['Education', 'Marital_Status'], drop_first=True)

#Checking target
df['Response'].value_counts()

import matplotlib.pyplot as plt

counts = df['Response'].value_counts().sort_index()

plt.figure(figsize=(6,4))
counts.plot(kind='bar')
plt.title('Class Imbalance in Response')
plt.xlabel('Response Class')
plt.ylabel('Number of Customers')
plt.xticks([0, 1], ['0 = No', '1 = Yes'], rotation=0)
plt.show()

# Train.Test split
from sklearn.model_selection import train_test_split

X = df.drop('Response', axis=1)
y = df['Response']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

importance_gb = pd.Series(gb.feature_importances_, index=X.columns)
importance_gb.sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

importance_gb.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Customer Response")
plt.gca().invert_yaxis()
plt.show()


# =============================================================================
# ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗███╗   ███╗███████╗███╗   ██╗████████╗
# ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝████╗ ████║██╔════╝████╗  ██║╚══██╔══╝
# ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ ██╔████╔██║█████╗  ██╔██╗ ██║   ██║
# ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  ██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║
# ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║███████╗██║ ╚████║   ██║
# ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
# =============================================================================

# =============================================================================
# SECTION 6 — DEPLOYMENT
# =============================================================================
#
# OVERVIEW
# --------
# Our Gradient Boosting Classifier (selected as the best-performing model)
# is deployed as an interactive Streamlit web application. The app allows
# marketing teams to:
#   1. Upload new customer CSV data and automatically retrain the model.
#   2. View model performance metrics (Accuracy, Precision, Recall, F1).
#   3. Explore the Top 10 features that drive campaign response.
#   4. Enter individual customer attributes and receive a live
#      "Likely to Respond / Unlikely to Respond" prediction with a
#      confidence probability.
#
# DEPLOYMENT ARCHITECTURE
# -----------------------
#   Phase 1 — Data & Training
#     • User uploads superstore_data.csv via the Streamlit sidebar.
#     • The preprocessing pipeline (null handling, age conversion, tenure
#       calculation, feature engineering, one-hot encoding) runs automatically.
#     • The Gradient Boosting model is trained in-session and cached using
#       @st.cache_data to avoid unnecessary re-training on reruns.
#
#   Phase 2 — Prediction Interface
#     • Marketing analysts enter customer attributes (income, age, recency,
#       spending, household size, etc.) via sliders and input fields.
#     • The trained model returns: predicted class (0/1) + probability score.
#     • A clear visual decision card ("✅ Likely" / "❌ Unlikely") is shown
#       alongside an actionable recommendation for the marketing team.
#
#   Phase 3 — Monitoring & Maintenance
#     • After each campaign, actual response outcomes are compared against
#       predictions to compute real-world F1-score.
#     • The model is scheduled for quarterly retraining as new customer
#       transaction data accumulates.
#     • Model versions are tracked (e.g., with MLflow or DVC) to enable
#       rollback if a new version underperforms.
#
# HOW TO RUN
# ----------
#   pip install streamlit scikit-learn pandas matplotlib
#   streamlit run streamlit_app.py
#
# =============================================================================


# =============================================================================
# ETHICAL CONSIDERATIONS
# =============================================================================
#
# 1. FAIRNESS & BIAS
#    The model is trained on historical marketing data. If past campaigns
#    were disproportionately targeted at — or withheld from — certain
#    demographic groups (e.g., customers with lower incomes or certain
#    marital statuses), those biases may be encoded in the model's learned
#    patterns. We regularly audit the feature importance rankings to ensure
#    protected or sensitive attributes are NOT the primary drivers of
#    predictions. If Age or Marital_Status appear in the top 3 features,
#    we investigate and consider removing or transforming those inputs.
#
# 2. TRANSPARENCY & EXPLAINABILITY
#    Gradient Boosting is not inherently human-interpretable (unlike
#    Logistic Regression). To maintain explainability:
#      • We publish the Top 10 Feature Importance chart in the app.
#      • We display the probability score alongside every prediction so
#        analysts understand how confident the model is.
#      • For high-stakes decisions, a SHAP (SHapley Additive exPlanations)
#        analysis can be added to explain individual predictions.
#
# 3. DATA PRIVACY (GDPR / CCPA)
#    Customer data includes income, purchase history, and household
#    demographics — all of which are personally sensitive. Mitigations:
#      • No PII (name, email, address) is used as a model feature.
#      • Data is processed in-session only; Streamlit does not persist
#        uploaded CSVs to a server.
#      • In a production pipeline, data must be anonymized/pseudonymized
#        before ingestion.
#
# 4. INFORMED CONSENT
#    Customers whose data is used to train the model should be informed
#    (via privacy policy) that their purchase behavior influences which
#    marketing campaigns they receive. This aligns with GDPR Article 22
#    on automated decision-making.
#
# =============================================================================


# =============================================================================
# RISKS & MITIGATIONS
# =============================================================================
#
# RISK 1 — MODEL DRIFT
#   Description : Consumer behavior shifts seasonally and economically.
#                 A model trained on 2020–2022 data may perform poorly in 2025.
#   Mitigation  : Schedule quarterly retraining with the latest campaign data.
#                 Track F1-score (class 1) monthly against actual campaign
#                 outcomes. Set an alert threshold (e.g., F1 drops below 0.55)
#                 to trigger an early retraining cycle.
#
# RISK 2 — CLASS IMBALANCE
#   Description : Only ~15% of customers respond (class 1), so the model is
#                 incentivized to predict "No" for everyone and still achieve
#                 ~85% accuracy — which is misleading.
#   Mitigation  : We use stratify=y in train_test_split to preserve class
#                 ratios. We report Recall and F1 for class 1 (not just
#                 accuracy). Further options include SMOTE oversampling or
#                 adjusting class_weight='balanced' in GradientBoostingClassifier.
#
# RISK 3 — OVERRELIANCE ON MODEL OUTPUT
#   Description : Marketing teams may treat model predictions as absolute
#                 truth and stop applying human judgment, leading to missed
#                 opportunities or customer alienation.
#   Mitigation  : Frame the tool as a "prioritization aid," not an oracle.
#                 Display confidence scores prominently so analysts can
#                 apply discretion on borderline cases (e.g., 51% confidence).
#                 Require human sign-off before excluding any customer segment.
#
# RISK 4 — DATA LEAKAGE
#   Description : Features like Total_Spending or Total_Purchases could
#                 inadvertently include post-campaign transactions if the
#                 dataset is not sliced correctly, causing artificially
#                 inflated performance metrics.
#   Mitigation  : Enforce a strict temporal cutoff — only include customer
#                 data recorded *before* the campaign launch date. Validate
#                 the dataset's Dt_Customer range before each training run.
#
# RISK 5 — FEEDBACK LOOP
#   Description : If the model consistently targets the same customer segments,
#                 those segments become the only ones measured for response,
#                 creating a self-reinforcing loop that ignores untested segments.
#   Mitigation  : Randomly include a small holdout group (~5%) in each campaign
#                 regardless of model prediction to continuously gather
#                 unbiased ground-truth data from the full customer population.
#
# =============================================================================


# =============================================================================
# SAVE TRAINED MODEL (for production use)
# =============================================================================

import joblib

# Save the best model (Gradient Boosting) to disk
joblib.dump(gb, 'campaign_response_model.pkl')
print("✅ Model saved as 'campaign_response_model.pkl'")

# Save the feature column list to ensure consistent input format
import json
with open('feature_columns.json', 'w') as f:
    json.dump(X.columns.tolist(), f)
print("✅ Feature columns saved as 'feature_columns.json'")

# Load the model later with:
#   gb_loaded = joblib.load('campaign_response_model.pkl')
#   y_pred = gb_loaded.predict(X_new)
