# -*- coding: utf-8 -*-
"""APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIEvMY1V0yXduRKeL1JSOWxS4g_vB2Ux
"""

import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("/content/sample_data/superstore_data.csv")

df['Income'] = df['Income'].fillna(df['Income'].median())

current_year = datetime.datetime.now().year
df['Age'] = current_year - df['Year_Birth']
df = df.drop('Year_Birth', axis=1)
df = df[(df['Age'] > 18) & (df['Age'] < 90)]

df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])
df['Customer_Tenure'] = (pd.Timestamp.now() - df['Dt_Customer']).dt.days
df = df.drop('Dt_Customer', axis=1)

spending_cols = ['MntWines','MntFruits','MntMeatProducts',
                 'MntFishProducts','MntSweetProducts','MntGoldProds']
df['Total_Spending'] = df[spending_cols].sum(axis=1)

df['Total_Purchases'] = (df['NumWebPurchases'] +
                         df['NumCatalogPurchases'] +
                         df['NumStorePurchases'])

df = df.drop('Id', axis=1)

df = pd.get_dummies(df, columns=['Education', 'Marital_Status'], drop_first=True)

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

X = df.drop('Response', axis=1)
y = df['Response']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Logistic Regression
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("=== Logistic Regression ===")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Random Forest
rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print("=== Random Forest ===")
print(classification_report(y_test, y_pred_rf))

# Gradient Boosting
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)
print("=== Gradient Boosting ===")
print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

# Feature Importance
importance_gb = pd.Series(gb.feature_importances_, index=X.columns)
importance_gb.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Customer Response")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# =============================================================================
# SECTION 6 — INTERACTIVE DEPLOYMENT (in Colab)
# =============================================================================

import ipywidgets as widgets
from IPython.display import display, HTML

# ── Styled Header ─────────────────────────────────────────────────────────────
display(HTML("""
<div style="background: linear-gradient(135deg, #4f46e5, #7c3aed);
            padding: 24px; border-radius: 12px; color: white; margin-bottom: 20px;">
    <h2 style="margin:0;">📊 Customer Campaign Response Predictor</h2>
    <p style="margin:4px 0 0;">Powered by Gradient Boosting — Enter a customer profile to predict campaign response</p>
</div>
"""))

# ── Input Widgets ─────────────────────────────────────────────────────────────
display(HTML("<h3>👤 Enter Customer Profile</h3>"))

income = widgets.IntSlider(value=55000, min=0, max=200000, step=1000,
                           description='Income ($):', style={'description_width': '150px'},
                           layout=widgets.Layout(width='500px'))

age = widgets.IntSlider(value=42, min=18, max=89, step=1,
                        description='Age:', style={'description_width': '150px'},
                        layout=widgets.Layout(width='500px'))

recency = widgets.IntSlider(value=30, min=0, max=100, step=1,
                            description='Days Since Purchase:', style={'description_width': '150px'},
                            layout=widgets.Layout(width='500px'))

total_spend = widgets.IntSlider(value=600, min=0, max=2500, step=50,
                                description='Total Spending ($):', style={'description_width': '150px'},
                                layout=widgets.Layout(width='500px'))

total_purch = widgets.IntSlider(value=10, min=0, max=30, step=1,
                                description='Total Purchases:', style={'description_width': '150px'},
                                layout=widgets.Layout(width='500px'))

wines = widgets.IntSlider(value=200, min=0, max=1500, step=10,
                          description='Wine Spending ($):', style={'description_width': '150px'},
                          layout=widgets.Layout(width='500px'))

meat = widgets.IntSlider(value=100, min=0, max=1500, step=10,
                         description='Meat Spending ($):', style={'description_width': '150px'},
                         layout=widgets.Layout(width='500px'))

kidhome = widgets.Dropdown(options=[0, 1, 2], value=0,
                           description='Kids at Home:', style={'description_width': '150px'},
                           layout=widgets.Layout(width='500px'))

teenhome = widgets.Dropdown(options=[0, 1, 2], value=0,
                            description='Teens at Home:', style={'description_width': '150px'},
                            layout=widgets.Layout(width='500px'))

tenure = widgets.IntSlider(value=1200, min=100, max=4000, step=50,
                           description='Tenure (days):', style={'description_width': '150px'},
                           layout=widgets.Layout(width='500px'))

num_deals = widgets.IntSlider(value=2, min=0, max=15, step=1,
                              description='Deal Purchases:', style={'description_width': '150px'},
                              layout=widgets.Layout(width='500px'))

num_web_vis = widgets.IntSlider(value=5, min=0, max=20, step=1,
                                description='Web Visits/Month:', style={'description_width': '150px'},
                                layout=widgets.Layout(width='500px'))

# Display all widgets
display(income, age, recency, total_spend, total_purch,
        wines, meat, kidhome, teenhome, tenure, num_deals, num_web_vis)

# ── Predict Button ────────────────────────────────────────────────────────────
predict_btn = widgets.Button(
    description='🔮 Predict Response',
    button_style='primary',
    layout=widgets.Layout(width='300px', height='45px', margin='20px 0px')
)

output = widgets.Output()

def on_predict(b):
    with output:
        output.clear_output()

        # Build input row
        input_data = {col: 0 for col in X.columns}
        input_data.update({
            'Income'           : income.value,
            'Age'              : age.value,
            'Kidhome'          : kidhome.value,
            'Teenhome'         : teenhome.value,
            'Recency'          : recency.value,
            'Customer_Tenure'  : tenure.value,
            'Total_Spending'   : total_spend.value,
            'Total_Purchases'  : total_purch.value,
            'MntWines'         : wines.value,
            'MntMeatProducts'  : meat.value,
            'NumDealsPurchases': num_deals.value,
            'NumWebVisitsMonth': num_web_vis.value,
        })

        X_input = pd.DataFrame([input_data])[X.columns]
        pred    = gb.predict(X_input)[0]
        proba   = gb.predict_proba(X_input)[0][1]

        if pred == 1:
            display(HTML(f"""
            <div style="background: linear-gradient(135deg, #dc2626, #db2777);
                        padding: 24px; border-radius: 12px; color: white;
                        text-align: center; font-size: 1.3rem; font-weight: 600; margin-top: 16px;">
                ✅ Likely to Respond &nbsp;|&nbsp; Confidence: {proba:.1%}
            </div>
            <div style="background: #f0fdf4; border: 1px solid #bbf7d0;
                        border-radius: 10px; padding: 16px; margin-top: 12px;">
                💡 <strong>Recommendation:</strong> Include this customer in the next campaign wave.
                High-confidence responders drive ROI.
            </div>
            """))
        else:
            display(HTML(f"""
            <div style="background: linear-gradient(135deg, #059669, #0d9488);
                        padding: 24px; border-radius: 12px; color: white;
                        text-align: center; font-size: 1.3rem; font-weight: 600; margin-top: 16px;">
                ❌ Unlikely to Respond &nbsp;|&nbsp; Confidence: {(1-proba):.1%} not responding
            </div>
            <div style="background: #fef2f2; border: 1px solid #fecaca;
                        border-radius: 10px; padding: 16px; margin-top: 12px;">
                💡 <strong>Recommendation:</strong> Deprioritize for this campaign.
                Consider a re-engagement offer instead.
            </div>
            """))

        # ── Feature Importance Chart ───────────────────────────────────────
        display(HTML("<h3 style='margin-top:24px;'>🔍 Top Features Driving This Prediction</h3>"))
        top10 = importance_gb.sort_values(ascending=False).head(10)
        colors = ['#4f46e5' if i < 3 else '#a5b4fc' for i in range(10)]
        fig, ax = plt.subplots(figsize=(8, 5))
        top10[::-1].plot(kind='barh', ax=ax, color=colors[::-1], edgecolor='none')
        ax.set_xlabel("Feature Importance Score")
        ax.set_title("Top 10 Features Influencing Customer Response", fontweight='bold')
        ax.spines[['top', 'right']].set_visible(False)
        plt.tight_layout()
        plt.show()

predict_btn.on_click(on_predict)
display(predict_btn, output)

# ── Ethics & Risks Section ────────────────────────────────────────────────────
display(HTML("""
<div style="margin-top: 40px;">
<h3>⚖️ Ethical Considerations</h3>

<div style="background:#fefce8; border:1px solid #fde68a; border-radius:10px;
            padding:16px; margin-bottom:10px;">
    <strong>🔶 Fairness & Bias</strong><br>
    Historical data may encode bias toward certain demographics.
    We audit feature importance regularly to ensure sensitive attributes
    like Age or Marital Status are not the primary drivers of predictions.
</div>

<div style="background:#fefce8; border:1px solid #fde68a; border-radius:10px;
            padding:16px; margin-bottom:10px;">
    <strong>🔶 Transparency & Explainability</strong><br>
    The Top 10 Feature Importance chart ensures stakeholders understand
    what drives each prediction. Probability scores are shown alongside
    every result so analysts can apply their own judgment.
</div>

<div style="background:#fefce8; border:1px solid #fde68a; border-radius:10px;
            padding:16px; margin-bottom:10px;">
    <strong>🔶 Data Privacy (GDPR / CCPA)</strong><br>
    No PII such as name or email is used as a model feature.
    Data is processed in-session only and never stored server-side.
</div>

<div style="background:#fefce8; border:1px solid #fde68a; border-radius:10px;
            padding:16px; margin-bottom:10px;">
    <strong>🔶 Informed Consent</strong><br>
    Customers should be notified that their purchase behavior influences
    which marketing campaigns they receive.
</div>

<h3 style="margin-top:24px;">⚠️ Risks & Mitigations</h3>

<div style="background:#fef2f2; border:1px solid #fecaca; border-radius:10px;
            padding:16px; margin-bottom:6px;">
    <strong>🔴 Model Drift</strong><br>
    Consumer behavior changes over time, degrading model accuracy.
</div>
<div style="background:#f0fdf4; border:1px solid #bbf7d0; border-radius:10px;
            padding:16px; margin-bottom:16px;">
    ✅ <strong>Mitigation:</strong> Retrain quarterly. Monitor F1-score monthly.
    Alert if F1 drops below 0.55.
</div>

<div style="background:#fef2f2; border:1px solid #fecaca; border-radius:10px;
            padding:16px; margin-bottom:6px;">
    <strong>🔴 Class Imbalance</strong><br>
    Only ~15% of customers respond, so the model may favour predicting No.
</div>
<div style="background:#f0fdf4; border:1px solid #bbf7d0; border-radius:10px;
            padding:16px; margin-bottom:16px;">
    ✅ <strong>Mitigation:</strong> Stratified splits, always report Recall and F1 for class 1.
</div>

<div style="background:#fef2f2; border:1px solid #fecaca; border-radius:10px;
            padding:16px; margin-bottom:6px;">
    <strong>🔴 Overreliance on Model Output</strong><br>
    Teams may stop applying human judgment and follow predictions blindly.
</div>
<div style="background:#f0fdf4; border:1px solid #bbf7d0; border-radius:10px;
            padding:16px; margin-bottom:16px;">
    ✅ <strong>Mitigation:</strong> Frame as a prioritization aid, not a final decision.
    Require human sign-off before excluding any customer segment.
</div>

<div style="background:#fef2f2; border:1px solid #fecaca; border-radius:10px;
            padding:16px; margin-bottom:6px;">
    <strong>🔴 Data Leakage</strong><br>
    Post-campaign transactions in Total Spending may inflate performance metrics.
</div>
<div style="background:#f0fdf4; border:1px solid #bbf7d0; border-radius:10px;
            padding:16px; margin-bottom:16px;">
    ✅ <strong>Mitigation:</strong> Enforce a temporal cutoff — only use data
    recorded before the campaign launch date.
</div>

<div style="background:#fef2f2; border:1px solid #fecaca; border-radius:10px;
            padding:16px; margin-bottom:6px;">
    <strong>🔴 Feedback Loop</strong><br>
    Always targeting the same segments creates a blind spot for untested customers.
</div>
<div style="background:#f0fdf4; border:1px solid #bbf7d0; border-radius:10px;
            padding:16px; margin-bottom:16px;">
    ✅ <strong>Mitigation:</strong> Randomly include a 5% holdout group in each
    campaign regardless of prediction to collect unbiased ground-truth data.
</div>

</div>
"""))