# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALfoKV0iLDkhiA3ezuks_EY-0Rb8yC7o
"""

# -*- coding: utf-8 -*-
import pandas as pd
df = pd.read_csv("/content/sample_data/superstore_data.csv")

df.head()
df.shape
df.info()
df.describe()

df.head()

df.isnull().sum()

#Handle Null Values
df['Income'] = df['Income'].fillna(df['Income'].median())

#Convert to age
import datetime

current_year = datetime.datetime.now().year
df['Age'] = current_year - df['Year_Birth']

df = df.drop('Year_Birth', axis=1)

#Remove unrealistic ages
df = df[(df['Age'] > 18) & (df['Age'] < 90)]

#Converting dt customer to tenure
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])

df['Customer_Tenure'] = (pd.Timestamp.now() - df['Dt_Customer']).dt.days

df = df.drop('Dt_Customer', axis=1)

#Create total spending
spending_cols = [
    'MntWines','MntFruits','MntMeatProducts',
    'MntFishProducts','MntSweetProducts','MntGoldProds'
]

df['Total_Spending'] = df[spending_cols].sum(axis=1)

# Create total purchases
df['Total_Purchases'] = (
    df['NumWebPurchases'] +
    df['NumCatalogPurchases'] +
    df['NumStorePurchases']
)

df = df.drop('Id', axis=1)

# Dummy Encoding
df = pd.get_dummies(df, columns=['Education', 'Marital_Status'], drop_first=True)

#Checking target
df['Response'].value_counts()

import matplotlib.pyplot as plt

counts = df['Response'].value_counts().sort_index()

plt.figure(figsize=(6,4))
counts.plot(kind='bar')
plt.title('Class Imbalance in Response')
plt.xlabel('Response Class')
plt.ylabel('Number of Customers')
plt.xticks([0, 1], ['0 = No', '1 = Yes'], rotation=0)
plt.show()

# Train Test split
from sklearn.model_selection import train_test_split

X = df.drop('Response', axis=1)
y = df['Response']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

importance_gb = pd.Series(gb.feature_importances_, index=X.columns)
importance_gb.sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

importance_gb.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Customer Response")
plt.gca().invert_yaxis()
plt.show()


# =============================================================================
# SECTION 6 — DEPLOYMENT (Streamlit)
# =============================================================================

#

# =============================================================================
# SECTION 6 — DEPLOYMENT
# =============================================================================
#
# The Gradient Boosting Classifier is deployed as an interactive Streamlit
# web application hosted on Streamlit Cloud via GitHub.
#
# DEPLOYMENT ARCHITECTURE
# -----------------------
# Phase 1 — Model Training
#   - User uploads superstore_data.csv via the Streamlit sidebar
#   - The full preprocessing pipeline runs automatically (null handling,
#     age conversion, tenure calculation, feature engineering, encoding)
#   - The Gradient Boosting model trains in-session and is cached to
#     avoid unnecessary re-training on reruns
#
# Phase 2 — Prediction Interface
#   - Marketing analysts enter customer attributes via sliders and inputs
#   - The model returns a predicted class (0 or 1) + probability score
#   - A visual decision card shows Likely or Unlikely to Respond alongside
#     an actionable recommendation for the marketing team
#
# Phase 3 — Monitoring & Maintenance
#   - After each campaign, actual outcomes are compared to predictions
#     to compute real-world F1-score
#   - Model is retrained quarterly as new transaction data accumulates
#   - Model versions are tracked to allow rollback if performance drops
#
# HOW IT IS DEPLOYED
# ------------------
#   - app.py and requirements.txt are pushed to GitHub
#   - Streamlit Cloud connects to the GitHub repo and serves the app
#   - No hardcoded file paths — data is uploaded live via the sidebar
#   - Live app URL is shared with the marketing team for daily use
#
# =============================================================================


# =============================================================================
# ETHICAL CONSIDERATIONS
# =============================================================================
#
# 1. FAIRNESS & BIAS
#    The model learns from historical marketing data. If past campaigns were
#    disproportionately aimed at or withheld from certain groups such as
#    lower-income customers or specific marital statuses, those patterns get
#    encoded into the model. We regularly audit the feature importance chart
#    to ensure sensitive attributes like Age or Marital_Status are NOT the
#    top drivers of predictions. If they appear in the top 3 we investigate
#    and consider removing or transforming those inputs.
#
# 2. TRANSPARENCY & EXPLAINABILITY
#    Gradient Boosting is not easily human-interpretable on its own. To
#    maintain transparency:
#      - We publish the Top 10 Feature Importance chart in the app so
#        stakeholders can see what the model is relying on
#      - Probability scores are shown alongside every prediction so analysts
#        understand how confident the model is
#      - For high-stakes decisions, SHAP (SHapley Additive exPlanations)
#        can be added to explain individual-level predictions
#
# 3. DATA PRIVACY (GDPR / CCPA)
#    Customer data includes income, purchase history, and household
#    demographics which are all personally sensitive. Mitigations:
#      - No direct PII such as name, email, or address is used as a feature
#      - Data is processed in-session only and never stored server-side
#      - In a production pipeline, data must be anonymized before ingestion
#
# 4. INFORMED CONSENT
#    Customers whose data trains the model should be notified via privacy
#    policy that their purchase behavior influences which marketing campaigns
#    they receive. This aligns with GDPR Article 22 on automated
#    decision-making affecting individuals.
#
# =============================================================================


# =============================================================================
# RISKS & MITIGATIONS
# =============================================================================
#
# RISK 1 — MODEL DRIFT
#   Description : Consumer behavior changes over time due to economic shifts,
#                 seasons, and trends. A model trained on older data may
#                 perform poorly on future campaigns.
#   Mitigation  : Schedule quarterly retraining with the latest campaign data.
#                 Monitor F1-score for class 1 monthly against real outcomes.
#                 Set an alert if F1 drops below 0.55 to trigger early retraining.
#
# RISK 2 — CLASS IMBALANCE
#   Description : Only ~15% of customers respond (class 1). A naive model can
#                 reach ~85% accuracy by always predicting No which is
#                 useless for identifying actual responders.
#   Mitigation  : We use stratify=y in train_test_split to preserve class ratios.
#                 We report Recall and F1 for class 1 not just overall accuracy.
#                 Additional options include SMOTE oversampling or class_weight tuning.
#
# RISK 3 — OVERRELIANCE ON MODEL OUTPUT
#   Description : Marketing teams may treat predictions as absolute and remove
#                 human judgment potentially alienating customers.
#   Mitigation  : Frame the tool as a prioritization aid not a final decision.
#                 Show confidence scores so analysts can apply discretion on
#                 borderline cases. Require human sign-off before excluding
#                 any customer segment.
#
# RISK 4 — DATA LEAKAGE
#   Description : Features like Total_Spending could include post-campaign
#                 transactions if the dataset is not filtered correctly,
#                 causing inflated and misleading performance metrics.
#   Mitigation  : Enforce a strict temporal cutoff — only include customer
#                 data recorded before the campaign launch date. Validate
#                 the date range before every training run.
#
# RISK 5 — FEEDBACK LOOP
#   Description : If the model always targets the same segments those are
#                 the only groups measured for response, creating a blind
#                 spot for untested customer groups.
#   Mitigation  : Randomly include a small holdout group of around 5% in
#                 each campaign regardless of model prediction to continuously
#                 collect unbiased ground-truth data from the full population.
#
# =============================================================================

import streamlit as st
import pandas as pd
import datetime
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title="Campaign Response Predictor", page_icon="📊", layout="wide")

st.markdown("""
<style>
    .metric-card {
        background: white;
        border-radius: 12px;
        padding: 20px 24px;
        box-shadow: 0 1px 4px rgba(0,0,0,0.07);
        border-left: 4px solid #4f46e5;
        margin-bottom: 16px;
    }
    .metric-card h2 { margin: 0; font-size: 2rem; color: #1e1b4b; }
    .metric-card p  { margin: 4px 0 0; color: #6b7280; font-size: 0.85rem; }
    .predict-box {
        border-radius: 16px;
        padding: 28px;
        color: white;
        text-align: center;
        font-size: 1.3rem;
        font-weight: 600;
        margin-top: 16px;
    }
    .predict-box.no  { background: linear-gradient(135deg, #059669 0%, #0d9488 100%); }
    .predict-box.yes { background: linear-gradient(135deg, #dc2626 0%, #db2777 100%); }
    .ethics-box {
        background: #fefce8;
        border: 1px solid #fde68a;
        border-radius: 10px;
        padding: 16px 20px;
        margin-bottom: 10px;
    }
    .risk-box {
        background: #fef2f2;
        border: 1px solid #fecaca;
        border-radius: 10px;
        padding: 16px 20px;
        margin-bottom: 10px;
    }
    .mitigation-box {
        background: #f0fdf4;
        border: 1px solid #bbf7d0;
        border-radius: 10px;
        padding: 16px 20px;
        margin-bottom: 10px;
    }
</style>
""", unsafe_allow_html=True)

@st.cache_data
def load_and_train(uploaded_file):
    df = pd.read_csv(uploaded_file)

    df['Income'] = df['Income'].fillna(df['Income'].median())

    current_year = datetime.datetime.now().year
    df['Age'] = current_year - df['Year_Birth']
    df = df.drop('Year_Birth', axis=1)
    df = df[(df['Age'] > 18) & (df['Age'] < 90)]

    df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])
    df['Customer_Tenure'] = (pd.Timestamp.now() - df['Dt_Customer']).dt.days
    df = df.drop('Dt_Customer', axis=1)

    spending_cols = ['MntWines','MntFruits','MntMeatProducts',
                     'MntFishProducts','MntSweetProducts','MntGoldProds']
    df['Total_Spending'] = df[spending_cols].sum(axis=1)

    df['Total_Purchases'] = (df['NumWebPurchases'] +
                             df['NumCatalogPurchases'] +
                             df['NumStorePurchases'])

    if 'Id' in df.columns:
        df = df.drop('Id', axis=1)

    df = pd.get_dummies(df, columns=['Education','Marital_Status'], drop_first=True)

    X = df.drop('Response', axis=1)
    y = df['Response']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y)

    gb = GradientBoostingClassifier(random_state=42)
    gb.fit(X_train, y_train)

    y_pred = gb.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred)
    importance = pd.Series(gb.feature_importances_, index=X.columns)

    return gb, X.columns.tolist(), report, cm, importance, df

st.sidebar.title("📊 Campaign Predictor")
st.sidebar.markdown("Upload your dataset to train the model.")
uploaded = st.sidebar.file_uploader("Upload superstore_data.csv", type=["csv"])

st.title("📊 Customer Campaign Response Predictor")
st.markdown("**Powered by Gradient Boosting** — Find which customers will respond to marketing campaigns.")

if uploaded is None:
    st.info("👈 Upload your **superstore_data.csv** in the sidebar to get started.")

    tab1, tab2 = st.tabs(["🚀 Deployment Plan", "⚖️ Ethics & Risks"])

    with tab1:
        st.header("Deployment Architecture")
        st.markdown("""
        **Phase 1 — Model Training**
        - CSV upload triggers the full preprocessing and training pipeline automatically
        - Model is cached so re-uploads do not re-train unnecessarily

        **Phase 2 — Prediction Interface**
        - Marketing teams enter customer attributes via sliders and dropdowns
        - Model returns a live prediction with a probability confidence score

        **Phase 3 — Monitoring & Retraining**
        - Track prediction accuracy against actual campaign results
        - Retrain quarterly with fresh data to avoid model drift
        """)

    with tab2:
        st.header("⚖️ Ethical Considerations")
        for title, body in [
            ("Fairness & Bias", "Historical data may encode bias toward certain demographics. We audit feature importance regularly to ensure sensitive attributes are not the primary drivers."),
            ("Transparency", "The Top 10 Feature Importance chart ensures stakeholders understand what drives each prediction."),
            ("Data Privacy (GDPR/CCPA)", "No PII is used as a model feature. Data is processed in-session only and never stored server-side."),
            ("Informed Consent", "Customers should be notified that their purchase behavior influences which campaigns they receive."),
        ]:
            st.markdown(f"<div class='ethics-box'><strong>🔶 {title}</strong><br>{body}</div>", unsafe_allow_html=True)

        st.header("⚠️ Risks & Mitigations")
        for risk, desc, mit in [
            ("Model Drift", "Consumer behavior shifts over time, degrading model accuracy.", "Retrain quarterly and monitor F1-score monthly against real campaign outcomes."),
            ("Class Imbalance", "Only ~15% of customers respond, so the model may favour predicting No.", "Use stratified splits and always report Recall and F1 for class 1, not just accuracy."),
            ("Overreliance", "Marketing teams may stop applying human judgment and follow predictions blindly.", "Frame the tool as a prioritization aid. Require human sign-off before excluding any segment."),
            ("Data Leakage", "Post-campaign transactions in Total_Spending may inflate performance metrics.", "Enforce a strict temporal cutoff — only use data recorded before the campaign launch date."),
        ]:
            st.markdown(f"<div class='risk-box'><strong>🔴 {risk}</strong><br>{desc}</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='mitigation-box'><strong>✅ Mitigation:</strong> {mit}</div>", unsafe_allow_html=True)

else:
    with st.spinner("Training model..."):
        gb, feature_cols, report, cm, importance, df = load_and_train(uploaded)

    st.success("✅ Model trained successfully!")

    tab1, tab2, tab3, tab4 = st.tabs([
        "📈 Model Performance", "🔍 Feature Importance",
        "🧑 Predict a Customer", "⚖️ Ethics & Risks"
    ])

    with tab1:
        st.header("Model Performance — Gradient Boosting")
        col1, col2, col3, col4 = st.columns(4)
        for col, (label, val) in zip([col1,col2,col3,col4], [
            ("Accuracy", f"{report['accuracy']:.2%}"),
            ("Precision (Class 1)", f"{report['1']['precision']:.2%}"),
            ("Recall (Class 1)", f"{report['1']['recall']:.2%}"),
            ("F1-Score (Class 1)", f"{report['1']['f1-score']:.2%}"),
        ]):
            col.markdown(f"<div class='metric-card'><h2>{val}</h2><p>{label}</p></div>", unsafe_allow_html=True)

        st.subheader("Confusion Matrix")
        fig, ax = plt.subplots(figsize=(5, 3.5))
        im = ax.imshow(cm, cmap='Blues')
        ax.set_xticks([0,1]); ax.set_yticks([0,1])
        ax.set_xticklabels(['Predicted No','Predicted Yes'])
        ax.set_yticklabels(['Actual No','Actual Yes'])
        for i in range(2):
            for j in range(2):
                ax.text(j, i, cm[i,j], ha='center', va='center', fontsize=14,
                        fontweight='bold', color='white' if cm[i,j] > cm.max()/2 else 'black')
        plt.colorbar(im, ax=ax)
        plt.tight_layout()
        st.pyplot(fig)

    with tab2:
        st.header("Top Features Driving Campaign Response")
        top10 = importance.sort_values(ascending=False).head(10)
        fig2, ax2 = plt.subplots(figsize=(8, 5))
        colors = ['#4f46e5' if i < 3 else '#a5b4fc' for i in range(10)]
        top10[::-1].plot(kind='barh', ax=ax2, color=colors[::-1], edgecolor='none')
        ax2.set_xlabel("Feature Importance Score")
        ax2.set_title("Top 10 Features Influencing Customer Response", fontweight='bold')
        ax2.spines[['top','right']].set_visible(False)
        plt.tight_layout()
        st.pyplot(fig2)

    with tab3:
        st.header("🧑 Predict: Will This Customer Respond?")
        with st.form("predict_form"):
            col_a, col_b, col_c = st.columns(3)
            with col_a:
                income      = st.number_input("Annual Income ($)", 0, 200000, 55000, step=1000)
                age         = st.slider("Age", 18, 89, 42)
                kidhome     = st.selectbox("Kids at Home", [0, 1, 2])
                teenhome    = st.selectbox("Teens at Home", [0, 1, 2])
            with col_b:
                recency     = st.slider("Days Since Last Purchase", 0, 100, 30)
                tenure      = st.number_input("Customer Tenure (days)", 100, 4000, 1200, step=50)
                total_spend = st.number_input("Total Spending ($)", 0, 2500, 600, step=50)
                total_purch = st.slider("Total Purchases", 0, 30, 10)
            with col_c:
                wines       = st.number_input("Wine Spending ($)", 0, 1500, 200, step=10)
                meat        = st.number_input("Meat Spending ($)", 0, 1500, 100, step=10)
                num_deals   = st.slider("Purchases via Deals", 0, 15, 2)
                num_web_vis = st.slider("Web Visits / Month", 0, 20, 5)
            submitted = st.form_submit_button("🔮 Predict Response")

        if submitted:
            input_data = {col: 0 for col in feature_cols}
            input_data.update({
                'Income': income, 'Age': age, 'Kidhome': kidhome,
                'Teenhome': teenhome, 'Recency': recency,
                'Customer_Tenure': tenure, 'Total_Spending': total_spend,
                'Total_Purchases': total_purch, 'MntWines': wines,
                'MntMeatProducts': meat, 'NumDealsPurchases': num_deals,
                'NumWebVisitsMonth': num_web_vis,
            })
            X_input = pd.DataFrame([input_data])[feature_cols]
            pred  = gb.predict(X_input)[0]
            proba = gb.predict_proba(X_input)[0][1]

            if pred == 1:
                st.markdown(f"<div class='predict-box yes'>✅ Likely to Respond &nbsp;|&nbsp; Confidence: {proba:.1%}</div>", unsafe_allow_html=True)
                st.info("💡 Include this customer in the next campaign wave.")
            else:
                st.markdown(f"<div class='predict-box no'>❌ Unlikely to Respond &nbsp;|&nbsp; Confidence: {1-proba:.1%} not responding</div>", unsafe_allow_html=True)
                st.info("💡 Deprioritize for this campaign. Consider a re-engagement offer instead.")

    with tab4:
        st.header("⚖️ Ethical Considerations")
        for title, body in [
            ("Fairness & Bias", "Historical data may encode bias toward certain demographics. We audit feature importance regularly."),
            ("Transparency", "Feature importance chart ensures stakeholders understand what drives predictions."),
            ("Data Privacy (GDPR/CCPA)", "No PII is used as a feature. Data is processed in-session only."),
            ("Informed Consent", "Customers should know their behavior influences which campaigns they receive."),
        ]:
            st.markdown(f"<div class='ethics-box'><strong>🔶 {title}</strong><br>{body}</div>", unsafe_allow_html=True)

        st.header("⚠️ Risks & Mitigations")
        for risk, desc, mit in [
            ("Model Drift", "Behavior shifts over time degrade accuracy.", "Retrain quarterly, monitor F1 monthly."),
            ("Class Imbalance", "Only ~15% respond, model may favour predicting No.", "Stratified splits, report Recall for class 1."),
            ("Overreliance", "Teams may stop using human judgment.", "Frame as prioritization aid, not final decision."),
            ("Data Leakage", "Post-campaign data may inflate metrics.", "Enforce temporal cutoff before campaign date."),
        ]:
            st.markdown(f"<div class='risk-box'><strong>🔴 {risk}</strong><br>{desc}</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='mitigation-box'><strong>✅ Mitigation:</strong> {mit}</div>", unsafe_allow_html=True)

st.markdown("---")
st.markdown("<center><small>Campaign Response Predictor · Gradient Boosting · Built with Streamlit</small></center>", unsafe_allow_html=True)